site_name: Girl Develop It

docs_dir: sources

theme: readthedocs

pages:
  - Home: 'index.md'
  - Installation (Website): installation.md
  - Installation (Docs): installation_docs.md
  - Deploying to Heroku: 'deploying.md'
  - Contribution Guidelines: 'contribution.md'
  - Frequently Asked Questions: 'faq.md'
